name: Lint
on: [push, pull_request]
jobs:
  lint:
    uses: open-contracting/.github/.github/workflows/lint.yml@main
    permissions:
      contents: write
    with:
      python-version: '3.12'
      # google and oauth2client are optional (try-except block).
      standard-maintenance-scripts-ignore: google,oauth2client
